blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ë¬¸ì˜ ë˜ëŠ” ê¸°íƒ€ ì œì•ˆ
    url: https://github.com/seoultech-EC-TCP-NL-hackathon/Team10-Decimal/discussions
    about: ì¼ë°˜ì ì¸ ì§ˆë¬¸ì´ë‚˜ í† ë¡ ì€ Discussions íƒ­ì„ ì´ìš©í•´ì£¼ì„¸ìš”.
